branch-defaults:
  main:
    environment: your-environment-name
environment-defaults:
  your-environment-name:
    branch: null
    repository: null
global:
  application_name: your-app-name
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application